
DROP TABLE IF EXISTS MEMBER CASCADE;
DROP TABLE IF EXISTS PRODUCT CASCADE;
DROP TABLE IF EXISTS FUNDING CASCADE;

CREATE TABLE PRODUCT (
     PRODUCT_ID bigint  not null generated by default as identity,
     PRODUCT_NAME varchar(255) not null,
     TARGET_FUNDING_PRICE integer not null,
     TOTAL_FUNDING_PRICE integer not null,
     FUNDING_STATUS varchar(30) not null,
     START_DATE timestamp not null,
     FINISH_DATE timestamp not null,
     FUNDING_MEMBER_NUMBER integer not null,
     -- VERSION integer,
     primary key (PRODUCT_ID)
);

CREATE TABLE MEMBER (
    MEMBER_ID bigint not null generated by default as identity,
    MEMBER_NAME varchar(255) not null,
    CREATED_AT timestamp,
    primary key (MEMBER_ID)
);

CREATE TABLE FUNDING (
     FUNDING_ID bigint not null generated by default as identity,
     FUNDING_PRICE integer not null,
     FUNDING_DATE timestamp,
     PRODUCT_ID bigint not null,
     MEMBER_ID bigint not null,
     primary key(FUNDING_ID),
     CONSTRAINT FK_FUNDING_TO_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
     CONSTRAINT FK_FUNDING_TO_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

